web/epaper/urls.py
# epaper/urls.py

from django.urls import path

from . import views

urlpatterns = [
    path('epaper/', views.EPaperView.as_view(), name='epaper'),
    path('thanks/', views.EPaperThanksView.as_view(), name='thanks'),
    path('directthanks/', views.EPaperHomeDirectThanksView.as_view(), name='homedirectthanks'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

web/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products import views

urlpatterns = [
    path('', views.HomeView.as_view()),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('epaper/', include(('epaper.urls', 'epaper'), namespace='epaper')),
    path('customers/', include(('customers.urls', 'customers'), namespace='customers')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# 新增 media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/orders/urls.py
# orders/urls.py

from django.urls import path

from . import views

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('addcart/<int:product_id>/', views.AddCartView.as_view(), name='add_cart'),
    path('deletecart/<int:product_id>/', views.DeleteCartView.as_view(), name='delete_cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('ecpay/', views.ECPayView.as_view(), name='ecpay'),
    path('return/', views.ReturnView.as_view(), name='return'),
    path('orderresult/', views.OrderResultView.as_view(), name='orderresult'),
    path('order_success/', views.OrderSuccessView.as_view(), name='order_success'),
    path('order_fail/', views.OrderFailView.as_view(), name='order_fail'),
]

web/products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('list/', views.ProductListView.as_view(), name='list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='detail'),
]

web/products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _ # 匯入 gettext_lazy 函數
from core import helpers as core_helpers
from django.utils.translation import get_language

# Create your models here.

class ProductCategory(models.Model):
    '''
    商品分類模型
    '''
    name = models.CharField('商品分類名稱', max_length=50)
    name_en = models.CharField('商品分類名稱(英)', max_length=50, null=True, blank=True)         # new
    description = models.TextField('商品分類描述', max_length=500, null=True, blank=True)
    description_en = models.TextField('商品分類描述(英)', max_length=500, null=True, blank=True) # new
    created = models.DateTimeField('建立日期', auto_now_add=True)
    modified = models.DateTimeField('修改日期', auto_now=True)
    image = models.ImageField("圖片", null=True, blank=True, upload_to=core_helpers.upload_handle)
    
    @property
    def name_locale(self):
        language = get_language()
        if language == 'zh-hant':
            return f"{self.name}"
        elif language == 'en':
            return f"{self.name_en}"
        return f"{self.name}"
    
    @property
    def description_locale(self):
        language = get_language()
        if language == 'zh-hant':
            return f"{self.description}"
        elif language == 'en':
            return f"{self.description_en}"
        return f"{self.description}"

    class Meta:
        verbose_name = '商品分類'
        verbose_name_plural = '商品分類'
        ordering = ['-created']

    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    '''
    商品模型
    '''
    name = models.CharField(_('Product Name'), max_length=50)
    name_en = models.CharField(_('Product Name En'), max_length=50, null=True, blank=True)
    description = models.TextField(_('Product Description'), max_length=500, null=True, blank=True)
    description_en = models.TextField(_('Product Description En'), max_length=500, null=True, blank=True)
    price = models.PositiveIntegerField(_('Product Price'), default=0)
    created = models.DateTimeField(_('Created Date'), auto_now_add=True)
    modified = models.DateTimeField(_('Modified Date'), auto_now=True)
    category = models.ForeignKey(
        'products.ProductCategory', blank=True, null=True, 
        on_delete=models.RESTRICT, verbose_name=_('Product Category'), related_name='product_set'
    ) # 新增 category 欄位

    @property
    def name_locale(self):
        language = get_language()
        if language == 'zh-hant':
            return f"{self.name}"
        elif language == 'en':
            return f"{self.name_en}"
        return f"{self.name}"
    
    @property
    def description_locale(self):
        language = get_language()
        if language == 'zh-hant':
            return f"{self.description}"
        elif language == 'en':
            return f"{self.description_en}"
        return f"{self.description}"

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Product')
        ordering = ['-created']

    def __str__(self):
        return f'{self.name}'
    
class ProductImage(models.Model):
    name = models.CharField('商品圖片說明', max_length=50)
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE, related_name='product_image_set')
    image = models.ImageField("圖片", null=True, blank=True, upload_to=core_helpers.upload_handle)
    order = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = '商品圖片'
        verbose_name_plural = '商品圖片'
        ordering = ['order']

    def __str__(self):
        return f'{self.name}'
    
class RelationalProduct(models.Model):
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE, verbose_name='商品名稱')
    order = models.ForeignKey('orders.Order', on_delete=models.CASCADE)
    number = models.IntegerField('數量', default=1)

    @property
    def name(self):
        return self.product.name

    @property
    def price(self):
        return self.product.price

    def __str__(self):
        return ""

web/products/views.py
from django.views.generic import TemplateView, ListView, DetailView
from products.models import Product, ProductCategory
from core.models import Setting

from products.documents import ProductDocument
from django.db import connection

class HomeView(TemplateView):
    template_name = "products/home.html"

    def get(self, request, *args, **kwargs):
        products = Product.objects.all()
        left_product_categories = ProductCategory.objects.all()[0:2]
        right_product_categories = ProductCategory.objects.all()[2:3]
        right_product_category = right_product_categories.first() if right_product_categories else None
        context = self.get_context_data(**kwargs)
        context['items'] = products
        context['schema_name'] = connection.schema_name
        context['left_product_categories'] = left_product_categories
        context['right_product_category'] = right_product_category
        return self.render_to_response(context)

class ProductListView(ListView):
    model = Product
    template_name = 'products/list.html'
    context_object_name = 'items'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        
        self.query_string = request.GET.get('q', '')
        self.object_list = self.get_queryset()
            
        context = self.get_context_data()
        if self.query_string:
            count = self.object_list.count()
            context['query_string'] = self.query_string
            context['count'] = count
        else:
            context['query_string'] = ''
            context['count'] = 0
        return self.render_to_response(context)

    def get_queryset(self):
        results = ProductDocument.search().query("term", **{"_routing": connection.schema_name})
        if self.query_string:
            results = results.query("match", name=self.query_string)
        return results

class ProductDetailView(DetailView):
    model = Product
    #template_name = 'products/detail.html'
    context_object_name = 'item'

    def get_template_names(self):
        """
        Return a list of template names to be used for the request. Must return
        a list. May not be called if render_to_response() is overridden.
        """
        setting = Setting.objects.get(id='zh-hant')
        template_name = 'products/detail/template1.html'
        
        if setting.detail_template == "Template-1":
            template_name = "products/detail/template1.html"
        elif setting.detail_template == "Template-2":
            template_name = "products/detail/template2.html"
        return [template_name]

web/products/templates/base.html
<!-- products/templates/base.html -->
{% load static %}
{% load i18n %}
{% load core_tag %}
{% get_current_language as LANGUAGE_CODE %}
{% get_setting as get_setting %}
{% get_setting_list as get_setting_list %}

<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="zh-hant">
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Skeens | E-commerce</title>

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Construction Html5 Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name="author" content="Themefisher">
  <meta name="generator" content="Themefisher Constra HTML Template v1.0">
  
  <!-- theme meta -->
  <meta name="theme-name" content="aviato" />
  
  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="{% get_media_prefix %}{{ get_setting.favicon }}" />
  
  <!-- Themefisher Icon font -->
  <link rel="stylesheet" href="{% static 'products/plugins/themefisher-font/style.css' %}">
  <!-- bootstrap.min css -->
  <link rel="stylesheet" href="{% static 'products/plugins/bootstrap/css/bootstrap.min.css' %}">
  
  <!-- Animate css -->
  <link rel="stylesheet" href="{% static 'products/plugins/animate/animate.css' %}">
  <!-- Slick Carousel -->
  <link rel="stylesheet" href="{% static 'products/plugins/slick/slick.css' %}">
  <link rel="stylesheet" href="{% static 'products/plugins/slick/slick-theme.css' %}">
  
  <!-- Main Stylesheet -->
  {% if get_setting.style %}
  <link rel="stylesheet" href="{% get_media_prefix %}{{ get_setting.style }}">
  {% else %}
  <link rel="stylesheet" href="{% static 'products/css/style.css' %}">
  {% endif %}

</head>

<body id="body">

<!-- Start Top Header Bar -->
<section class="top-header">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-xs-12 col-sm-4">
				<!--<img style="height: 12em;width: 12em" src="{% get_media_prefix %}{{ get_setting.logo }}">-->
				<div class="contact-number">
					<i class="tf-ion-android-mail"></i>
					<span>{{ get_setting.email }}</span>
					<!-- 訂閱電子報 -->
                    <!--<span><a href="{% url 'epaper:epaper' %}">{% translate 'Subscribe to the newsletter' %}</a></span>-->
				</div>
			</div>
			<div class="col-md-4 col-xs-12 col-sm-4">
				<!-- Site Logo -->
				<div class="logo text-center">
					<a href="{% url 'products:home' %}">
						<!-- replace logo here -->
						<svg width="135px" height="29px" viewBox="0 0 155 29" version="1.1" xmlns="http://www.w3.org/2000/svg"
							xmlns:xlink="http://www.w3.org/1999/xlink">
							<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" font-size="40"
								font-family="AustinBold, Austin" font-weight="bold">
								<g id="Group" transform="translate(-108.000000, -297.000000)" fill="#000000">
									<text id="sitename">
										<tspan x="108.94" y="325">{{ get_setting.sitename }}</tspan>
									</text>
								</g>
							</g>
						</svg>
					</a>
				</div>
			</div>
			<div class="col-md-4 col-xs-12 col-sm-4">
				<!-- Cart -->
				<ul class="top-menu text-right list-inline">
					<li class="dropdown cart-nav dropdown-slide">
						<a href="#!" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"><i
								class="tf-ion-android-cart"></i>Cart</a>
						<div class="dropdown-menu cart-dropdown">
							<ul class="text-center cart-buttons">
								<li><a href="{% url 'orders:cart' %}" class="btn btn-small">View Cart</a></li>
								<li><a href="checkout.html" class="btn btn-small btn-solid-border">Checkout</a></li>
							</ul>
						</div>
					</li><!-- / Cart -->

					<!-- Search -->
					<li class="dropdown search dropdown-slide">
						<a href="#!" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"><i
								class="tf-ion-ios-search-strong"></i> Search</a>
						<ul class="dropdown-menu search-dropdown">
							<li>
								<form method="GET" action="{% url 'products:list' %}" 
								onsubmit="this.action = this.action + this.search.value;alert(this.action); this.submit();">
								<input type="search" name="q" class="form-control" placeholder="Search..."/>
								</form>
							</li>
						</ul>
					</li><!-- / Search -->

					<!-- Languages -->
					<li class="commonSelect">
						<form action="{% url 'set_language' %}" method="post">
							{% csrf_token %}
							<input name="next" type="hidden" value="{{ redirect_to }}">
							<select name="language" class="form-control" onchange="this.form.submit()">
								{% for language in get_setting_list %}
									<option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
										{{ language.name_local }} ({{ language.code }})
									</option>
								{% endfor %}
							</select>
						</form>
					</li><!-- / Languages -->

				</ul><!-- / .nav .navbar-nav .navbar-right -->
			</div>
		</div>
	</div>
</section><!-- End Top Header Bar -->

{% block content %}
{% endblock content %}

<section class="section instagram-feed">
	<div class="container">
		<div class="row">
			<div class="title">
				<h2>View us on instagram</h2>
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<!--<div class="instagram-slider" id="instafeed" data-accessToken="IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"></div>
				-->
			</div>
		</div>
	</div>
</section>

<footer class="footer section text-center">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="social-media">
					<li>
						<a href="{{ get_setting.facebook }}" target="_blank" rel="noreferrer noopenner">
							<i class="tf-ion-social-facebook"></i>
						</a>
					</li>
					<li>
						<a href="{{ get_setting.instagram }}" target="_blank" rel="noreferrer noopenner">
							<i class="tf-ion-social-instagram"></i>
						</a>
					</li>
					<li>
						<a href="{{ get_setting.twitter }}" target="_blank" rel="noreferrer noopenner">
							<i class="tf-ion-social-twitter"></i>
						</a>
					</li>
				</ul>
				<ul class="footer-menu text-uppercase">
					<li>
						<a href="{% url 'epaper:contact' %}">{% translate 'CONTACT' %}</a>
					</li>
					<!--
					<li>
						<a href="shop.html">SHOP</a>
					</li>
					<li>
						<a href="pricing.html">Pricing</a>
					</li>-->
					<li>
						<a href="{% url 'epaper:contact' %}">{% translate 'PRIVACY POLICY' %}</a>
					</li>
				</ul>
				<p class="copyright-text">Copyright &copy;2023, Designed &amp; Developed by <a href="https://www.linkedin.com/in/ronald-tseng-259857273/">Ro</a></p>
			</div>
		</div>
	</div>
</footer>

    <!-- 
    Essential Scripts
    =====================================-->
    
    <!-- Main jQuery -->
    <script src="{% static 'products/plugins/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.1 -->
    <script src="{% static 'products/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Bootstrap Touchpin -->
    <script src="{% static 'products/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js' %}"></script>
    <!-- Instagram Feed Js -->
    <script src="{% static 'products/plugins/instafeed/instafeed.min.js' %}"></script>
    <!-- Video Lightbox Plugin -->
    <script src="{% static 'products/plugins/ekko-lightbox/dist/ekko-lightbox.min.js' %}"></script>
    <!-- Count Down Js -->
    <script src="{% static 'products/plugins/syo-timer/build/jquery.syotimer.min.js' %}"></script>

    <!-- slick Carousel -->
    <script src="{% static 'products/plugins/slick/slick.min.js' %}"></script>
    <script src="{% static 'products/plugins/slick/slick-animation.min.js' %}"></script>

    <!-- Google Mapl -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"></script>
    <script type="text/javascript" src="{% static 'products/plugins/google-map/gmap.js' %}"></script>

    <!-- Main Js File -->
    <script src="{% static 'products/js/script.js' %}"></script>
    
    <!-- sweetalert2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    <script>
        function getAjax(url, msg, reload){
            $.get(url, function(data, status){
                Swal.fire({
                    icon: 'success',
                    title: msg,
                    showConfirmButton: false,
                    timer: 1500
                }).then((result) => {
                    if (reload == 'true'){
                        location.reload()
                    }
                })
          });
        }
        
        
    </script>

  </body>
  </html>