web/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products import views

urlpatterns = [
    path('', views.HomeView.as_view()),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('epaper/', include(('epaper.urls', 'epaper'), namespace='epaper')),
    path('customers/', include(('customers.urls', 'customers'), namespace='customers')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# 新增 media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/orders/urls.py
# orders/urls.py

from django.urls import path

from . import views

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('addcart/<int:product_id>/', views.AddCartView.as_view(), name='add_cart'),
    path('deletecart/<int:product_id>/', views.DeleteCartView.as_view(), name='delete_cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('ecpay/', views.ECPayView.as_view(), name='ecpay'),
    path('return/', views.ReturnView.as_view(), name='return'),
    path('orderresult/', views.OrderResultView.as_view(), name='orderresult'),
    path('order_success/', views.OrderSuccessView.as_view(), name='order_success'),
    path('order_fail/', views.OrderFailView.as_view(), name='order_fail'),
]

web/products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('list/', views.ProductListView.as_view(), name='list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='detail'),
]

web/orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

class Order(models.Model):
    '''
    訂單
    '''
    order_id = models.CharField(_('Order Id'), max_length=20)
    email = models.EmailField('E-mail', max_length=255)
    product = models.ManyToManyField('products.Product', related_name='order_set', through='products.RelationalProduct')
    name = models.CharField(_('Name'), max_length=50)
    phone = models.CharField(_('Phone'), max_length=50)
    district = models.CharField(_('District'), max_length=50)
    zipcode = models.CharField(_('Zip Code'), max_length=50)
    address = models.CharField(_('Address'), max_length=255)
    total = models.PositiveIntegerField(_('Total'), default=0)
    created = models.DateTimeField(_('Created Date'), auto_now_add=True)
    modified = models.DateTimeField(_('Modified Date'), auto_now=True)
    status = models.CharField(
        _('Status'), 
        max_length=100, 
        choices=(("unpaid", _("Unpaid")), ("payment_fail", _("Payment Fail")), ("waiting_for_shipment", _("Waiting for shipment")), ("transporting", _("Transporting")), ("completed", _("Completed")), ("cancelled", _("Cancelled"))), 
        default="unpaid"
    )
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.order_id:
            self.order_id = f'ORDER{self.id:08}'
            super().save(*args, **kwargs)
    
    class Meta:
        verbose_name = '訂單'
        verbose_name_plural = '訂單'

    def __str__(self):
        return f'{self.order_id}'

web/orders/forms.py
from django import forms
from orders.models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'email',
            'name',
            'phone',
            'district',
            'zipcode',
            'address',
        )
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'zipcode': forms.TextInput(attrs={'class': 'form-control'}),
            'district': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
        }

web/orders/views.py
import base64
import pickle

from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View, TemplateView, FormView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from products.models import Product, RelationalProduct
from orders.models import Order
from orders.forms import OrderForm

from orders import ecpay_payment_sdk
import importlib.util
spec = importlib.util.spec_from_file_location(
    "ecpay_payment_sdk",
    "orders/ecpay_payment_sdk.py"
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
from datetime import datetime

class CartView(TemplateView):
    template_name = "orders/cart.html"

    def get(self, request, *args, **kwargs):
        cart_str = request.COOKIES.get('cart', '')
        product_dict = {}
        if cart_str:
            cart_bytes = cart_str.encode()
            cart_bytes = base64.b64decode(cart_bytes)
            cart_dict = pickle.loads(cart_bytes)
            product_dict = cart_dict.copy()
            for product_id in cart_dict:
                if product := Product.objects.filter(id=product_id):
                    product_dict[product_id]["product"] = product.first()
                else:
                    del product_dict[product_id]
        context = self.get_context_data(**kwargs)
        context["product_dict"] = product_dict
        return self.render_to_response(context)
    
class AddCartView(View):

    def get(self, request, *args, **kwargs):
        product_id = self.kwargs.get('product_id', '')
        cart_str = request.COOKIES.get('cart', '')
        if product_id:
            if cart_str:
                cart_bytes = cart_str.encode()
                cart_bytes = base64.b64decode(cart_bytes)
                cart_dict = pickle.loads(cart_bytes)
            else:
                cart_dict = {}
            if product_id in cart_dict:
                cart_dict[product_id]['count'] += 1
            else:
                cart_dict[product_id] = {
                    'count': 1,
                }
            cart_str = base64.b64encode(pickle.dumps(cart_dict)).decode()
        context = {}
        context["status"] = 200
        response = JsonResponse(context)
        response.set_cookie("cart", cart_str)
        return response
    
class DeleteCartView(View):

    def get(self, request, *args, **kwargs):
        product_id = self.kwargs.get('product_id', '')
        cart_str = request.COOKIES.get('cart', '')
        if product_id:
            if cart_str:
                cart_bytes = cart_str.encode()
                cart_bytes = base64.b64decode(cart_bytes)
                cart_dict = pickle.loads(cart_bytes)
            else:
                cart_dict = {}
            if product_id in cart_dict:
                del cart_dict[product_id]
            cart_str = base64.b64encode(pickle.dumps(cart_dict)).decode()
        context = {}
        context["status"] = 200
        response = JsonResponse(context)
        response.set_cookie("cart", cart_str)
        return response
    
class CheckoutView(FormView):
    template_name = "orders/checkout.html"   # 結帳頁面

    form_class = OrderForm
    success_url = 'orders/confirmation.html' # 前往付款頁面

    def get_cart_cookie(self, request):
        cart_str = request.COOKIES.get('cart', '')
        product_dict = {}
        print("cart_str: ", cart_str)
        if cart_str:
            cart_bytes = cart_str.encode()
            cart_bytes = base64.b64decode(cart_bytes)
            cart_dict = pickle.loads(cart_bytes)
        return cart_dict
    
    def get(self, request, *args, **kwargs):
        cart_dict = self.get_cart_cookie(request)
        if cart_dict:
            product_dict = cart_dict.copy()
            total = 0
            for product_id in cart_dict:
                if product := Product.objects.filter(id=product_id):
                    product_dict[product_id]["product"] = product.first()
                    total += int(product_dict[product_id]["count"]) * int(product.first().price)
                else:
                    del product_dict[product_id]
        context = self.get_context_data(**kwargs)
        context["product_dict"] = product_dict
        context["total"] = total
        for key, value in context.items():
            print("CheckoutView: ")
            print(key, value)
        return self.render_to_response(context)
    
    def form_valid(self, form):
        print("into form_valid")
        self.object = form.save(commit=False)
        cart_dict = self.get_cart_cookie(self.request)
        self.object.save()
        print("cart_dict:", cart_dict)
        if cart_dict:
            total = 0
            for product_id in cart_dict:
                if product := Product.objects.filter(id=product_id):
                    RelationalProduct.objects.create(order=self.object, product=product.first(), number=cart_dict[product_id]["count"])
                    total += int(cart_dict[product_id]["count"]) * int(product.first().price)
        self.object.total = total
        self.object.save()
        context = self.get_context_data(form=form)
        context['order_id'] = self.object.order_id
        for key, value in context.items():
            print("form_valid: ")
            print(key, value)
        return render(self.request, self.success_url, context=context)
    
class ECPayView(TemplateView):
    template_name = "orders/ecpay.html"

    def post(self, request, *args, **kwargs):
        scheme = request.is_secure() and "https" or "http"
        domain = request.META['HTTP_HOST']

        order_id = request.POST.get("order_id")
        order = Order.objects.get(order_id=order_id)
        product_list = "#".join([product.name for product in order.product.all()])
        order_params = {
            'MerchantTradeNo': order.order_id,
            'StoreID': '',
            'MerchantTradeDate': datetime.now().strftime("%Y/%m/%d %H:%M:%S"),
            'PaymentType': 'aio',
            'TotalAmount': order.total,
            'TradeDesc': order.order_id,
            'ItemName': product_list,
            'ReturnURL': f'{scheme}://{domain}/orders/return/', # ReturnURL為付款結果通知回傳網址，為特店server或主機的URL，用來接收綠界後端回傳的付款結果通知。
            'ChoosePayment': 'ALL',
            'ClientBackURL': f'{scheme}://{domain}/products/list/', # 消費者點選此按鈕後，會將頁面導回到此設定的網址(返回商店按鈕)
            'ItemURL': f'{scheme}://{domain}/products/list/', # 商品銷售網址
            'Remark': '交易備註',
            'ChooseSubPayment': '',
            'OrderResultURL': f'{scheme}://{domain}/orders/orderresult/', # 消費者付款完成後，綠界會將付款結果參數以POST方式回傳到到該網址
            'NeedExtraPaidInfo': 'Y',
            'DeviceSource': '',
            'IgnorePayment': '',
            'PlatformID': '',
            'InvoiceMark': 'N',
            'CustomField1': '',
            'CustomField2': '',
            'CustomField3': '',
            'CustomField4': '',
            'EncryptType': 1,
        }
        # 建立實體
        ecpay_payment_sdk = module.ECPayPaymentSdk(
            MerchantID='2000132',
            HashKey='5294y06JbISpM5x9',
            HashIV='v77hoKGq4kWxNNIS'
        )
        # 產生綠界訂單所需參數
        final_order_params = ecpay_payment_sdk.create_order(order_params)

        # 產生 html 的 form 格式
        action_url = 'https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5'  # 測試環境
        # action_url = 'https://payment.ecpay.com.tw/Cashier/AioCheckOut/V5' # 正式環境
        ecpay_form = ecpay_payment_sdk.gen_html_post_form(action_url, final_order_params)
        context = self.get_context_data(**kwargs)
        context['ecpay_form'] = ecpay_form
        return self.render_to_response(context)
    
class ReturnView(View):
    
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(ReturnView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        ecpay_payment_sdk = module.ECPayPaymentSdk(
            MerchantID='2000132',
            HashKey='5294y06JbISpM5x9',
            HashIV='v77hoKGq4kWxNNIS'
        )
        res = request.POST.dict()
        back_check_mac_value = request.POST.get('CheckMacValue')
        check_mac_value = ecpay_payment_sdk.generate_check_value(res)
        if check_mac_value == back_check_mac_value:
            return HttpResponse('1|OK')
        return HttpResponse('0|Fail')
    
class OrderResultView(View):
    
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(OrderResultView, self).dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):

        ecpay_payment_sdk = module.ECPayPaymentSdk(
            MerchantID='2000132',
            HashKey='5294y06JbISpM5x9',
            HashIV='v77hoKGq4kWxNNIS'
        )
        res = request.POST.dict()
        back_check_mac_value = request.POST.get('CheckMacValue')
        order_id = request.POST.get('MerchantTradeNo')
        rtnmsg = request.POST.get('RtnMsg')
        rtncode = request.POST.get('RtnCode')
        check_mac_value = ecpay_payment_sdk.generate_check_value(res)
        if check_mac_value == back_check_mac_value and rtnmsg == 'Succeeded' and rtncode == '1':
            order = Order.objects.get(order_id=order_id)
            order.status = 'waiting_for_shipment'
            order.save()
            return HttpResponseRedirect('/orders/order_success/')
        return HttpResponseRedirect('/orders/order_fail/')
    
class OrderSuccessView(TemplateView):
    template_name = "orders/order_success.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)
    
class OrderFailView(TemplateView):
    template_name = "orders/order_fail.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

web/orders/templates/orders/cart.html
<!-- orders/templates/orders/cart.html -->

{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Main Menu Section -->
<div class="page-wrapper">
    <div class="cart shopping">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <div class="block">
              <div class="product-list">
                <form method="post">
                  <table class="table">
                    <thead>
                      <tr>
                        <th class="">Item Name</th>
                        <th class="">Item Price</th>
                        <th class="">Quatity</th>
                        <th class="">Total Price</th>
                        <th class="">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for product_id, product in product_dict.items %}
                      <tr class="">
                        <td class="">
                          <div class="product-info">
                            {% if product.product.product_image_set.all %}
                              {% if product.product.product_image_set.all.0.image %}
                                <img width="80" src="{{ product.product.product_image_set.all.0.image.url }}" alt="" />
                              {% endif %}
                            {% endif %}
                            <a href="#!">{{ product.product.name }}</a>
                          </div>
                        </td>
                        <td class="">${{ product.product.price }}</td>
                        <td class="">
                          {{ product.count }}
                        </td>
                        <td class="">${% widthratio product.product.price 1 product.count %}</td>
                        <td class="">
							<a href="javascript:void(0)" onclick="getAjax('{% url 'orders:delete_cart' product_id %}', '已移除商品', 'true');" class="product-remove" >Remove</a>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <a href="{% url 'orders:checkout' %}" class="btn btn-main pull-right">Checkout</a>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
{% endblock content %}

web/orders/templates/orders/checkout.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<section class="page-header">
   <div class="container">
      <div class="row">
         <div class="col-md-6">
            <ol class="breadcrumb">
               <li><a href="{% url 'products:home' %}">{% translate "Home page" %}</a></li>
               <li><a href="{% url 'orders:cart' %}">{% translate "Shopping cart" %}</a></li>
               <li class="active">{% translate "Checkout" %}</li>
            </ol>
         </div>
   </div>
   </div>
</section>
<div class="page-wrapper">
   
   <div class="checkout shopping">
      <div class="container">
         <div class="row">
            <div class="col-md-8">
               <div class="block billing-details">
                  <h4 class="widget-title">Billing Details</h4>
                  <form method="post" class="checkout-form">
                     {% csrf_token %}
                     <div class="form-group">
                        <label for="name">{{ form.name.label }}</label>
                        {{ form.name }}
                     </div>
                     <div class="form-group">
                        <label for="email">{{ form.email.label }}</label>
                        {{ form.email }}
                     </div>
                     <div class="form-group">
                        <label for="phone">{{ form.phone.label }}</label>
                        {{ form.phone }}
                     </div>
                     <div class="checkout-country-code clearfix">
                        <div class="form-group">
                           <label for="zipcode">{{ form.zipcode.label }}</label>
                           {{ form.zipcode }}
                        </div>
                        <div class="form-group" >
                           <label for="district">{{ form.district.label }}</label>
                           {{ form.district }}
                        </div>
                     </div>
                     <div class="form-group">
                        <label for="address">{{ form.address.label }}</label>
                        {{ form.address }}
                     </div>
                     <input type="submit" class="btn btn-main mt-20" value="{% translate 'Place Order' %}">
                  </form>
               </div>
            </div>
            <div class="col-md-4">
               <div class="product-checkout-details">
                  <div class="block">
                     <h4 class="widget-title">Order Summary</h4>
                     {% for product_id, product in product_dict.items %}
                        <div class="media product-card">
                           <a class="pull-left" href="{% url 'products:detail' product_id %}">
                              {% if product.product.product_image_set.all %}
                                 {% if product.product.product_image_set.all.0.image %}
                                    <img class="media-object" src="{{ product.product.product_image_set.all.0.image.url }}" alt="Image" />
                                 {% endif %}
                              {% endif %}
                           </a>
                           <div class="media-body">
                              <h4 class="media-heading"><a href="{% url 'products:detail' product_id %}">{{ product.product.name }}</a></h4>
                              <p class="price">{{ product.count }} x ${{ product.product.price }}</p>
                              <a href="javascript:void(0)" onclick="getAjax('{% url 'orders:delete_cart' product_id %}', '已移除商品', 'true');" class="remove" >Remove</a>
                           </div>
                        </div>
                     {% endfor %}
                     <ul class="summary-prices"></ul>
                     <div class="summary-total">
                        <span>Total</span>
                        <span>${{ total }}</span>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- Modal -->
<div class="modal fade" id="coupon-modal" tabindex="-1" role="dialog">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-body">
            <form>
               <div class="form-group">
                  <input class="form-control" type="text" placeholder="Enter Coupon Code">
               </div>
               <button type="submit" class="btn btn-main">Apply Coupon</button>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

web/orders/templates/orders/confirmation.html
<!-- orders/templates/orders/confirmation.html -->

{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<!-- Page Wrapper -->
<section class="page-wrapper success-msg">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="block text-center">
          <i class="tf-ion-android-checkmark-circle"></i>
          <h2 class="text-center">訂單已建立完成，請立即前往付款</h2>
          <form method="post" action="{% url 'orders:ecpay' %}">
            {% csrf_token %}
            <input type="hidden" name="order_id" value="{{ order_id }}" />
            <button type="submit" class="btn btn-main">前往付款</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section><!-- /.page-warpper -->
{% endblock content %}

web/orders/templates/orders/ecpay.html
<!-- orders/templates/orders/ecpay.html -->

{% autoescape off %}{{ecpay_form}}{% endautoescape %}

web/orders/templates/orders/order_fail.html
<!-- orders/templates/orders/order_fail.html -->

{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<!-- Page Wrapper -->
<section class="page-wrapper success-msg">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="block text-center">
          <i class="tf-ion-android-checkmark-circle"></i>
          <h2 class="text-center">付款失敗，請重新下單</h2>
          <a href="shop.html" class="btn btn-main mt-20">Continue Shopping</a>
        </div>
      </div>
    </div>
  </div>
</section><!-- /.page-warpper -->
{% endblock content %}

web/orders/templates/orders/order_success.html
<!-- orders/templates/orders/order_success.html -->

{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<!-- Page Wrapper -->
<section class="page-wrapper success-msg">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="block text-center">
          <i class="tf-ion-android-checkmark-circle"></i>
          <h2 class="text-center">付款成功</h2>
          <a href="shop.html" class="btn btn-main mt-20">Continue Shopping</a>
        </div>
      </div>
    </div>
  </div>
</section><!-- /.page-warpper -->
{% endblock content %}