web/epaper/urls.py
# epaper/urls.py

from django.urls import path

from . import views

urlpatterns = [
    path('epaper/', views.EPaperView.as_view(), name='epaper'),
    path('thanks/', views.EPaperThanksView.as_view(), name='thanks'),
    path('directthanks/', views.EPaperHomeDirectThanksView.as_view(), name='homedirectthanks'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

web/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products import views

urlpatterns = [
    path('', views.HomeView.as_view()),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('epaper/', include(('epaper.urls', 'epaper'), namespace='epaper')),
    path('customers/', include(('customers.urls', 'customers'), namespace='customers')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# 新增 media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/orders/urls.py
# orders/urls.py

from django.urls import path

from . import views

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('addcart/<int:product_id>/', views.AddCartView.as_view(), name='add_cart'),
    path('deletecart/<int:product_id>/', views.DeleteCartView.as_view(), name='delete_cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('ecpay/', views.ECPayView.as_view(), name='ecpay'),
    path('return/', views.ReturnView.as_view(), name='return'),
    path('orderresult/', views.OrderResultView.as_view(), name='orderresult'),
    path('order_success/', views.OrderSuccessView.as_view(), name='order_success'),
    path('order_fail/', views.OrderFailView.as_view(), name='order_fail'),
]

web/products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('list/', views.ProductListView.as_view(), name='list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='detail'),
]

web/products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _ # 匯入 gettext_lazy 函數
from core import helpers as core_helpers
from django.utils.translation import get_language

# Create your models here.

class ProductCategory(models.Model):
    '''
    商品分類模型
    '''
    name = models.CharField('商品分類名稱', max_length=50)
    name_en = models.CharField('商品分類名稱(英)', max_length=50, null=True, blank=True)         # new
    description = models.TextField('商品分類描述', max_length=500, null=True, blank=True)
    description_en = models.TextField('商品分類描述(英)', max_length=500, null=True, blank=True) # new
    created = models.DateTimeField('建立日期', auto_now_add=True)
    modified = models.DateTimeField('修改日期', auto_now=True)
    image = models.ImageField("圖片", null=True, blank=True, upload_to=core_helpers.upload_handle)
    
    @property
    def name_locale(self):
        language = get_language()
        if language == 'zh-hant':
            return f"{self.name}"
        elif language == 'en':
            return f"{self.name_en}"
        return f"{self.name}"
    
    @property
    def description_locale(self):
        language = get_language()
        if language == 'zh-hant':
            return f"{self.description}"
        elif language == 'en':
            return f"{self.description_en}"
        return f"{self.description}"

    class Meta:
        verbose_name = '商品分類'
        verbose_name_plural = '商品分類'
        ordering = ['-created']

    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    '''
    商品模型
    '''
    name = models.CharField(_('Product Name'), max_length=50)
    name_en = models.CharField(_('Product Name En'), max_length=50, null=True, blank=True)
    description = models.TextField(_('Product Description'), max_length=500, null=True, blank=True)
    description_en = models.TextField(_('Product Description En'), max_length=500, null=True, blank=True)
    price = models.PositiveIntegerField(_('Product Price'), default=0)
    created = models.DateTimeField(_('Created Date'), auto_now_add=True)
    modified = models.DateTimeField(_('Modified Date'), auto_now=True)
    category = models.ForeignKey(
        'products.ProductCategory', blank=True, null=True, 
        on_delete=models.RESTRICT, verbose_name=_('Product Category'), related_name='product_set'
    ) # 新增 category 欄位

    @property
    def name_locale(self):
        language = get_language()
        if language == 'zh-hant':
            return f"{self.name}"
        elif language == 'en':
            return f"{self.name_en}"
        return f"{self.name}"
    
    @property
    def description_locale(self):
        language = get_language()
        if language == 'zh-hant':
            return f"{self.description}"
        elif language == 'en':
            return f"{self.description_en}"
        return f"{self.description}"

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Product')
        ordering = ['-created']

    def __str__(self):
        return f'{self.name}'
    
class ProductImage(models.Model):
    name = models.CharField('商品圖片說明', max_length=50)
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE, related_name='product_image_set')
    image = models.ImageField("圖片", null=True, blank=True, upload_to=core_helpers.upload_handle)
    order = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = '商品圖片'
        verbose_name_plural = '商品圖片'
        ordering = ['order']

    def __str__(self):
        return f'{self.name}'
    
class RelationalProduct(models.Model):
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE, verbose_name='商品名稱')
    order = models.ForeignKey('orders.Order', on_delete=models.CASCADE)
    number = models.IntegerField('數量', default=1)

    @property
    def name(self):
        return self.product.name

    @property
    def price(self):
        return self.product.price

    def __str__(self):
        return ""

web/products/views.py
from django.views.generic import TemplateView, ListView, DetailView
from products.models import Product, ProductCategory
from core.models import Setting

from products.documents import ProductDocument
from django.db import connection

class HomeView(TemplateView):
    template_name = "products/home.html"

    def get(self, request, *args, **kwargs):
        products = Product.objects.all()
        left_product_categories = ProductCategory.objects.all()[0:2]
        right_product_categories = ProductCategory.objects.all()[2:3]
        right_product_category = right_product_categories.first() if right_product_categories else None
        context = self.get_context_data(**kwargs)
        context['items'] = products
        context['schema_name'] = connection.schema_name
        context['left_product_categories'] = left_product_categories
        context['right_product_category'] = right_product_category
        return self.render_to_response(context)

class ProductListView(ListView):
    model = Product
    template_name = 'products/list.html'
    context_object_name = 'items'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        
        self.query_string = request.GET.get('q', '')
        self.object_list = self.get_queryset()
            
        context = self.get_context_data()
        if self.query_string:
            count = self.object_list.count()
            context['query_string'] = self.query_string
            context['count'] = count
        else:
            context['query_string'] = ''
            context['count'] = 0
        return self.render_to_response(context)

    def get_queryset(self):
        results = ProductDocument.search().query("term", **{"_routing": connection.schema_name})
        if self.query_string:
            results = results.query("match", name=self.query_string)
        return results

class ProductDetailView(DetailView):
    model = Product
    #template_name = 'products/detail.html'
    context_object_name = 'item'

    def get_template_names(self):
        """
        Return a list of template names to be used for the request. Must return
        a list. May not be called if render_to_response() is overridden.
        """
        setting = Setting.objects.get(id='zh-hant')
        template_name = 'products/detail/template1.html'
        
        if setting.detail_template == "Template-1":
            template_name = "products/detail/template1.html"
        elif setting.detail_template == "Template-2":
            template_name = "products/detail/template2.html"
        return [template_name]

web/products/templates/products/home.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<div class="hero-slider">
	{% for imageurl in get_setting.slide_images %}
	{% if imageurl %}
	<div class="slider-item th-fullpage hero-area" style="background-image: url({% get_media_prefix %}{{ imageurl }});">
	{% endif %}
	  <div class="container">
		<div class="row">
		  {% if forloop.counter == 1 %}
		  <div class="col-lg-8 text-center">
		  {% endif %}
		  {% if forloop.counter == 2 %}
		  <div class="col-lg-8 text-left">
		  {% endif %}
		  {% if forloop.counter == 3 %}
		  <div class="col-lg-8 text-right">
		  {% endif %}
			<p data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".1">PRODUCTS</p>
			<h1 data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".5">The beauty of nature <br> is hidden in details.</h1>
			<a data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".8" class="btn" href="#allitem">Shop Now</a>
		  </div>
		</div>
	  </div>
	</div>
	{% endfor %}
</div>

<section class="product-category section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title text-center">
					{% if LANGUAGE_CODE == 'zh-hant' %}
					<h2>以商品分類尋找屬於您的商品</h2>
					{% elif LANGUAGE_CODE == 'en' %}
					<h2>Product category</h2>
					{% endif %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="category-box category-box-2">
                    <!--<div class="category-box">-->
                        <a href="#allitem">
                            {% if get_setting.home_type1.image %}
                                <img src="{% get_media_prefix %}{{ get_setting.home_type1.image }}" alt="" />
                            {% endif %}
                            <div class="content">
                                <h3 style="color: rgb(0, 0, 0);">{{ get_setting.home_type1.name }}</h3>
                                <p style="color: rgb(0, 0, 0);">{{ get_setting.home_type1.description }}</p>
                            </div>
                        </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="category-box category-box-2">
                    <a href="#allitem">
                        {% if get_setting.home_type2.image %}
                            <img src="{% get_media_prefix %}{{ get_setting.home_type2.image }}" alt="" />
                        {% endif %}
                        <div class="content">
                            <h3 style="color: rgb(0, 0, 0);">{{ get_setting.home_type2.name }}</h3>
                            <p style="color: rgb(0, 0, 0);">{{ get_setting.home_type2.description }}</p>
                        </div>
                    </a>
                </div>
            </div>
            <!--
			<div class="col-md-6">
                <div class="category-box category-box-3">
                    <a href="#!">
                        {% if get_setting.home_type3.image %}
                            <img src="{% get_media_prefix %}{{ get_setting.home_type3.image }}" alt="" />
                        {% endif %}
                        <div class="content">
                            <h3 style="color: rgb(0, 0, 0);">{{ get_setting.home_type3.name }}</h3>
                            <p style="color: rgb(0, 0, 0);">{{ get_setting.home_type3.description }}</p>
                        </div>
                    </a>
                </div>
            </div>-->
        </div>
    </div>
</section>

<section class="products section bg-gray">
    <div class="container">
        <div class="row">
            <div class="title text-center">
                <h2>所有商品</h2>
            </div>
        </div>
        <div class="row">
            {% for item in items %}
                <div class="col-md-4">
                    <div class="product-item">
                        <div id="allitem" class="product-thumb">
                            {% if item.product_image_set.all.0.image %}
                                <img class="img-responsive" src="{{ item.product_image_set.all.0.image.url }}" alt="product-img" />
                            {% endif %}
                            <div class="preview-meta">
                                <ul>
                                    <li>
                                        <span  data-toggle="modal" data-target="#product-modal-{{ item.id }}">
                                            <i class="tf-ion-ios-search-strong"></i>
                                        </span>
                                    </li>
                                    <li>
                                        <a href="#" ><i class="tf-ion-ios-heart"></i></a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0)" onclick="getAjax('{% url 'orders:add_cart' item.id %}', '已加入購物車', 'false');"><i class="tf-ion-android-cart"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="product-content">
                            <h4><a href="product-single.html">{{ item.name_locale }}</a></h4>
                            <p class="price">${{ item.price }}</p>
                        </div>
                    </div>
                </div>
                <!-- Modal -->
                <div class="modal product-modal fade" id="product-modal-{{ item.id }}">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i class="tf-ion-close"></i>
                    </button>
                    <div class="modal-dialog " role="document">
                        <div class="modal-content">
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-md-8 col-sm-6 col-xs-12">
                                        <div class="modal-image">
                                            {% if item.product_image_set.all.0.image %}
                                                <img class="img-responsive" src="{{ item.product_image_set.all.0.image.url }}" alt="product-img" />
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        <div class="product-short-details">
                                            <h2 class="product-title">{{ item.name_locale }}</h2>
                                            <p class="product-price">${{ item.price }}</p>
                                            <p class="product-short-description">
                                                {{ item.description_locale }}
                                            </p>
                                            <a href="javascript:void(0)" onclick="getAjax('{% url 'orders:add_cart' item.id %}', '已加入購物車', 'false')" class="btn btn-main">{% translate 'Add to cart' %}</a>
                                            <a href="{% url 'products:detail' item.id %}" class="btn btn-transparent">{% translate 'View detail of the product' %}</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- /.modal -->
            {% endfor %}
        </div>
    </div>
</section>

<section class="call-to-action bg-gray section">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<div class="title">
					<h2>SUBSCRIBE TO NEWSLETTER</h2>
				</div>
				<div class="col-lg-6 col-md-offset-3">
					<!-- /input-group
				    <div class="input-group subscription-form">
				      <input type="text" class="form-control" placeholder="Enter Your Email Address">
				      <span class="input-group-btn">
				        <button class="btn btn-main" type="button">Subscribe Now!</button>
				      </span>
				    </div> -->
					<form action="{% url 'epaper:homedirectthanks' %}" method="post" class="input-group subscription-form">
						{%csrf_token%}
						<input type="text" class="form-control" placeholder="Enter Your Email Address" name="inputemail">
						<span class="input-group-btn">
						  <button class="btn btn-main" type="submit">Subscribe Now!</button>
						</span>
					</form>
			  </div><!-- /.col-lg-6 -->

			</div>
		</div> 		<!-- End row -->
	</div>   	<!-- End container -->
</section>   <!-- End section -->
{% endblock content %}

web/products/templates/products/list.html
<!-- products/templates/products/list.html -->
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

<section class="page-header">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="content">
					<h1 class="page-name">
						{% if query_string %}
						{{query_string}} 的搜尋結果為 {{ count }} 筆
						{% else %}
							全部商品
						{% endif%}
					</h1>
					<ol class="breadcrumb">
						<li><a href="{% url 'products:home' %}">首頁</a></li>
						<li class="active"><a href="{% url 'products:list' %}">商品列表</a></li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</section>


<section class="products section">
	<div class="container">
		<div class="row">
			{% for item in items %}
			<div class="col-md-4">
				<div class="product-item">
					<div class="product-thumb">
						{% if item.product_image_set.0.image %}
						<img class="img-responsive" src="{{ item.product_image_set.0.image }}" alt="product-img" />
						{% endif %}
						<div class="preview-meta">
							<ul>
								<li>
									<span  data-toggle="modal" data-target="#product-modal-{{ item.id }}">
										<i class="tf-ion-ios-search-strong"></i>
									</span>
								</li>
								<li>
			                        <a href="#!" ><i class="tf-ion-ios-heart"></i></a>
								</li>
								<li>
									<a href="javascript:void(0)" onclick="getAjax('{% url 'orders:add_cart' item.id %}', '已加入購物車', 'false')"><i class="tf-ion-android-cart"></i></a>
								</li>
							</ul>
                      	</div>
					</div>
					<div class="product-content">
						<h4><a href="product-single.html">{{ item.name }}</a></h4>
						<p class="price">${{ item.price }}</p>
					</div>
				</div>
			</div>
		
		<!-- Modal -->
		<div class="modal product-modal fade" id="product-modal-{{ item.id }}">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<i class="tf-ion-close"></i>
			</button>
		  	<div class="modal-dialog " role="document">
		    	<div class="modal-content">
			      	<div class="modal-body">
			        	<div class="row">
			        		<div class="col-md-8 col-sm-6 col-xs-12">
			        			<div class="modal-image">
									{% if item.product_image_set.0.image %}
				        			<img class="img-responsive" src="{{ item.product_image_set.0.image }}" alt="product-img" />
									{% endif %}
			        			</div>
			        		</div>
			        		<div class="col-md-4 col-sm-6 col-xs-12">
			        			<div class="product-short-details">
			        				<h2 class="product-title">{{ item.name }}</h2>
			        				<p class="product-price">${{ item.price }}</p>
			        				<p class="product-short-description">
			        					{{ item.description }}
			        				</p>
									<a href="javascript:void(0)" onclick="getAjax('{% url 'orders:add_cart' item.id %}', '已加入購物車', 'false')" class="btn btn-main">{% translate 'Add to cart' %}</a>
			        				<a href="{% url 'products:detail' item.id %}" class="btn btn-transparent">{% translate 'View detail of the product' %}</a>
			        			</div>
			        		</div>
			        	</div>
			        </div>
		    	</div>
		  	</div>
		</div><!-- /.modal -->
		{% endfor %}
		</div>
	</div>
</section>

{% endblock content %}