web/customers/urls.py
from django.urls import path
from django.urls.conf import include

from . import views

urlpatterns = [
    path('form/', views.CustomersFormView.as_view(), name='customers_form'),
]

web/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products import views

urlpatterns = [
    path('', views.HomeView.as_view()),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('epaper/', include(('epaper.urls', 'epaper'), namespace='epaper')),
    path('customers/', include(('customers.urls', 'customers'), namespace='customers')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# 新增 media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/customers/models.py
import os
from django.conf import settings
from django.db import models, connection
from django_tenants.models import TenantMixin, DomainMixin
# Create your models here.

class Client(TenantMixin):
    name = models.CharField(max_length=100)
    paid_until = models.DateField()
    on_trial = models.BooleanField()
    created_on = models.DateField(auto_now_add=True)
    # default true, schema will be automatically created and synced when it is saved
    auto_create_schema = True

    auto_drop_schema = True

    def delete(self, force_drop=False, *args, **kwargs):
        """
        Deletes this row. Drops the tenant's schema if the attribute
        auto_drop_schema set to True.
        """
        locale_path = locale_path = os.path.join(settings.BASE_DIR, f'tenant_locale/{connection.schema_name}')
        os.system(f"rm -rf {locale_path}")
        self._drop_schema(force_drop)
        super().delete(*args, **kwargs)

class Domain(DomainMixin):
    pass

web/customers/forms.py
from django import forms
from django.db import models
from customers.models import Client, Domain

class CustomersForm(forms.Form):
    
    def __init__(self, *args, **kwargs):
        super(CustomersForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "租戶名稱"
        self.fields['from_schema_name'].label = "要複製的 schema 名稱"
        self.fields['to_schema_name'].label = "新增的 schema 名稱"
        self.fields['description'].label = "說明"
        self.fields['domain'].label = "網域"
    
    name = forms.CharField(required=True)
    from_schema_name = forms.CharField(required=True)
    to_schema_name = forms.CharField(required=True)
    description = forms.CharField(required=True)
    domain = forms.CharField(required=True)

    def clean_name(self):
        data = self.cleaned_data['name']
        if Client.objects.filter(name=data).exists():
            raise forms.ValidationError(f'租戶名稱 "{data}" 已存在。')
        return data

    def clean_from_schema_name(self):
        data = self.cleaned_data['from_schema_name']
        if not Client.objects.filter(schema_name=data).exists():
            raise forms.ValidationError(f'要複製的 schema 名稱 "{data}" 不存在。')
        return data
        
    def clean_to_schema_name(self):
        data = self.cleaned_data['to_schema_name']
        if '.' in data:
            raise forms.ValidationError(f'新建的 schema 名稱 "{data}" 不可包含 "." 字元。')
        if not data.isalnum() or data.isdigit():
            raise forms.ValidationError(f'新建的 schema 名稱 "{data}" 需英數字混和。')
        if Client.objects.filter(schema_name=data).exists():
            raise forms.ValidationError(f'新建的 schema 名稱 "{data}" 已存在。')
        return data
        
    def clean_domain(self):
        data = self.cleaned_data['domain']
        if Domain.objects.filter(domain=data).exists():
            raise forms.ValidationError(f'網域"{data}" 已存在。')
        return data

web/customers/views.py
# customers/views.py

import os
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import connection
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.views.generic.edit import FormView
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.urls import reverse

from django_tenants.management.commands.clone_tenant import Command

from customers.models import Client
from random import choice

from customers.forms import CustomersForm

@method_decorator(never_cache, name='dispatch')
class CustomersFormView(LoginRequiredMixin, FormView):
    login_url = '/admin/login/'
    template_name = 'customers/customers_form.html'
    form_class = CustomersForm

    def get_context_data(self, **kwargs):
        context = super(CustomersFormView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        now_schema_name = connection.schema_name
        name = form.cleaned_data['name']
        from_schema_name = form.cleaned_data['from_schema_name']
        to_schema_name = form.cleaned_data['to_schema_name']
        domain = form.cleaned_data['domain']
        description = form.cleaned_data['description']

        c = Command()
        tenant_data = {'schema_name': to_schema_name, 'name': name, 'description': description}
        tenant = c.store_tenant(clone_schema_from=from_schema_name,
                                    clone_tenant_fields=True,
                                    **tenant_data)
        tenant.name = name
        tenant.save()
        domain_data = {'domain': domain, 'tenant': tenant, 'is_primary': 'True'}
        domain = c.store_tenant_domain(**domain_data)
        connection.set_schema(now_schema_name)
        # locale dir
        from_locale_path = locale_path = os.path.join(settings.BASE_DIR, f'tenant_locale/{from_schema_name}')
        to_locale_path = locale_path = os.path.join(settings.BASE_DIR, f'tenant_locale/{to_schema_name}')
        if not os.path.isdir(to_locale_path):
            print(f"cp -pr {from_locale_path} {to_locale_path}")
            os.system(f"cp -pr {from_locale_path} {to_locale_path}")
        return HttpResponseRedirect(reverse('admin:customers_client_changelist'))

    def get_success_url(self):
        return reverse('admin:customers_client_changelist')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            context = self.get_context_data(**kwargs)
            request.current_app = 'admin'
            context.update(admin.site.each_context(request))
            return self.render_to_response(context)

    def get(self, request, *args, **kwargs):
        # 限制特定使用者才可進入該頁面
        if not request.user.username.startswith('admin') and not request.user.is_superuser:
            return HttpResponseRedirect(reverse('admin:index'))
        context = self.get_context_data(**kwargs)
        request.current_app = 'admin'
        context.update(admin.site.each_context(request))
        return self.render_to_response(context)

web/customers/templates/customers/change_list.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_list %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}">
  {% if cl.formset %}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">
  {% endif %}
  {% if cl.formset or action_form %}
    <script src="{% url 'admin:jsi18n' %}"></script>
  {% endif %}
  {{ media.css }}
  {% if not actions_on_top and not actions_on_bottom %}
    <style>
      #changelist table thead th:first-child {width: inherit}
    </style>
  {% endif %}
{% endblock %}

{% block extrahead %}
{{ block.super }}
{{ media.js }}
{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-list{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=cl.opts.app_label %}">{{ cl.opts.app_config.verbose_name }}</a>
&rsaquo; {{ cl.opts.verbose_name_plural|capfirst }}
</div>
{% endblock %}
{% endif %}

{% block coltype %}{% endblock %}

{% block content %}
  <div id="content-main">
    {% block object-tools %}
        <ul class="object-tools">
          {% block object-tools-items %}
            <li>
              <a href="{% url 'customers:customers_form' %}" class="not add_tenant">新增租戶</a>
            </li>
            {% if has_add_permission %}
            <li>
              {% url cl.opts|admin_urlname:'add' as add_url %}
              <a href="{% add_preserved_filters add_url is_popup to_field %}" class="addlink">
                {% blocktranslate with cl.opts.verbose_name as name %}Add {{ name }}{% endblocktranslate %}
              </a>
            </li>
            {% endif %}
          {% endblock %}
        </ul>
    {% endblock %}
    {% if cl.formset and cl.formset.errors %}
        <p class="errornote">
        {% if cl.formset.total_error_count == 1 %}{% translate "Please correct the error below." %}{% else %}{% translate "Please correct the errors below." %}{% endif %}
        </p>
        {{ cl.formset.non_form_errors }}
    {% endif %}
    <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
      <div class="changelist-form-container">
        {% block search %}{% search_form cl %}{% endblock %}
        {% block date_hierarchy %}{% if cl.date_hierarchy %}{% date_hierarchy cl %}{% endif %}{% endblock %}

        <form id="changelist-form" method="post"{% if cl.formset and cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
        {% if cl.formset %}
          <div>{{ cl.formset.management_form }}</div>
        {% endif %}

        {% block result_list %}
          {% if action_form and actions_on_top and cl.show_admin_actions %}{% admin_actions %}{% endif %}
          {% result_list cl %}
          {% if action_form and actions_on_bottom and cl.show_admin_actions %}{% admin_actions %}{% endif %}
        {% endblock %}
        {% block pagination %}{% pagination cl %}{% endblock %}
        </form>
      </div>
      {% block filters %}
        {% if cl.has_filters %}
          <div id="changelist-filter">
            <h2>{% translate 'Filter' %}</h2>
            {% if cl.has_active_filters %}<h3 id="changelist-filter-clear">
              <a href="{{ cl.clear_all_filters_qs }}">&#10006; {% translate "Clear all filters" %}</a>
            </h3>{% endif %}
            {% for spec in cl.filter_specs %}{% admin_list_filter cl spec %}{% endfor %}
          </div>
        {% endif %}
      {% endblock %}
    </div>
  </div>
{% endblock %}

web/customers/templates/customers/customers_form.html
<!-- customers/templates/customers/customers_form.html -->

{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
  {% if title %} › {% if back %} <a href="{{ back }}">{{ title }}</a> {% else %} {{ title }} {% endif %}{% endif %}
  {% if subtitle %} › {{ subtitle|safe }}{% endif %}
</div>
{% endblock %}

{% block content %}

<meta name="robots" content="NONE,NOARCHIVE" />
<style>

</style>

<div class="card">
  <div class="card-block">
    <div>
      <fieldset class="form module">
        <form id="form" name="form" method="post">
          {% csrf_token %}
          {{form.media}}
          <div class="col-xs-12 col-sm-9 col-md-10 col-multi-fields">
            <table border="0" width="100%">
              {% for field in form %}
                <tr>
                  <td colspan=2>
                    <div class="form-group row form-row">
                      <label class="form-control-label col-xs-12 col-sm-3 col-md-2 {% if field.field.required %} field-required{% endif %}"
                        id="{{ field.auto_id }}_filter" name="{{ field.name }}">{{field.label}}</label>
                      <div class="col-xs-9">{{field}}</div>
                      {% for error in field.errors %} 
                        {{ error }}
                      {% endfor %}
                    </div>
                  </td>
                </tr>
              {% endfor %}
              <tr>
                <td colspan=2> </td>
              </tr>
              <tr>
                <td colspan=2>
                  <center>
                    <button class="btn btn-primary" type="submit" value="新增" name="add">新增</button>
                  </center>
                </td>
              </tr>
            </table>
          </div>
        </form>
      </fieldset>
    </div>
  </div>
</div>

{% endblock %}